Vagrant.configure('2') do |config|
  config.vm.define 'master' do |web|
    web.vm.box = 'centos/7'
    web.vm.hostname = 'master'

    web.vm.network :private_network, ip: '192.168.0.2'
    web.vm.network :forwarded_port, guest: 22, host: 10122, id: 'ssh'


    web.vm.provider :virtualbox do |v|
      v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      v.customize ['modifyvm', :id, '--memory', 512]
      v.customize ['modifyvm', :id, '--name', 'master']
    end
  end

  config.vm.define 'minion' do |db|
    db.vm.box = 'centos/7'
    db.vm.hostname = 'minion'

    db.vm.network :private_network, ip: '192.168.0.3'
    db.vm.network :forwarded_port, guest: 22, host: 10222, id: 'ssh'

    db.vm.provider :virtualbox do |v|
      v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      v.customize ['modifyvm', :id, '--memory', 512]
      v.customize ['modifyvm', :id, '--name', 'minion']
    end
  end

end
